# This YAML file sets up a job that will build and publish a Python package
# when a new release is created.

name: Publish Package  # Name of the job

on:
  release:  # Trigger the job when a new release is created
    types: [created]

jobs:
  deploy:  # Define the deploy job
    runs-on: ubuntu-latest  # Use Ubuntu as the operating system

    steps:  # Define the steps that the job will take
      - name: Checkout  # Check out the code repository
        uses: actions/checkout@v3

      - name: Set up Python  # Set up the Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies  # Install project dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
          pip install -r requirements.txt

      - name: Build and Publish Package  # Build the package and publish it to PyPI
        env:
          user: ${{ secrets.PYPI_USERS }}  # Set the PyPI username from a secret in the repo setting add this as token name PYPI_USERS& in data give __token__
          password: ${{ secrets.PYPI_PASSWORD }}  # Set the PyPI password from a secret create it on pypi add token copy paste here
        run: |
          python setup.py sdist bdist_wheel  # Build the source and binary distributions
          twine upload --username $user --password $password dist/*  # Publish the package to PyPI using twine
